[env]
TERM = "xterm-256color"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "SemiBold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Light"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
padding = { x = 20, y = 20 }
dynamic_padding = true
decorations = "None"
opacity = 0.75
blur = true
startup_mode = "Maximized"

[colors.primary]
background = "#2f383e"
foreground = "#d3c6aa"

[colors.normal]
black   = "#272e33"
red     = "#e67e80"
green   = "#a7c080"
yellow  = "#dbbc7f"
blue    = "#7fbbb3"
magenta = "#d699b6"
cyan    = "#83c092"
white   = "#d3c6aa"

[colors.bright]
black   = "#2f383e"
red     = "#e67e80"
green   = "#a7c080"
yellow  = "#dbbc7f"
blue    = "#7fbbb3"
magenta = "#d699b6"
cyan    = "#83c092"
white   = "#f9f5d7"

