[env]
TERM = "xterm-256color"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "SemiBold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Light"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
padding = { x = 20, y = 20 }
dynamic_padding = true


decorations = "None"
opacity = 0.95
blur = true
startup_mode = "Maximized"

[colors.primary]
background = "#221a0f"
foreground = "#d3af86"

[colors.normal]
black = "#221a0f"
red = "#c87e5a"
green = "#879a6b"
yellow = "#e4b581"
blue = "#5d90cd"
magenta = "#c792ea"
cyan = "#6bbab2"
white = "#d3af86"

[colors.bright]
black = "#7d6f48"
red = "#c87e5a"
green = "#879a6b"
yellow = "#e4b581"
blue = "#5d90cd"
magenta = "#c792ea"
cyan = "#6bbab2"
white = "#f2cca8"

